igor: homework 24(selenium basics3) completed
eugene-okulik/python-magic pull request #155
Opened 2023-11-26 12:51 UTC by IgorMakhon

2023-12-01 12:58 UTC, eugene-okulik requested changes

2023-12-02 13:09 UTC, IgorMakhon commented on homework/igor_mahon/homework_24_selenium_basics3/test_task1.py
> +    driver.find_element(By.XPATH, "//div[@id='div_id_choose_language']/select/option[2]").click()
Да, спасибо!
dropdown.select_by_visible_text('Python')  - сработало, но не dropdown.select_by_value('Python')

2023-12-05 07:55 UTC, eugene-okulik commented on homework/igor_mahon/homework_24_selenium_basics3/test_task1.py
> +    driver.find_element(By.XPATH, "//div[@id='div_id_choose_language']/select/option[2]").click()
Это потому что у этой опции value не Python, а 1

2023-12-05 07:55 UTC, eugene-okulik approved these changes

2023-12-05 07:56 UTC, merged