igor: homework 3(dictionary) completed
eugene-okulik/python-magic pull request #17
Opened 2023-08-05 13:43 UTC by IgorMakhon

2023-08-07 06:19 UTC, eugene-okulik requested changes
Осталось поправить одну невнимательность

2023-08-07 06:19 UTC, eugene-okulik commented on homework/igor_mahon/homework_3_dictionary/task_dictionary.py
> +my_dict["dict"]["i am a tuple"] = "any_value"
Проверку на внимательность не прошел. В задании было:

> добавьте элемент с ключом ('i am a tuple',)

А ты выполнил как будто там:

> добавьте элемент с ключом "i am a tuple"

2023-08-07 07:29 UTC, IgorMakhon commented on homework/igor_mahon/homework_3_dictionary/task_dictionary.py
> +my_dict["dict"]["i am a tuple"] = "any_value"
Спасибо, подправил

2023-08-11 14:56 UTC, eugene-okulik approved these changes

2023-08-11 14:56 UTC, merged