KH: Homework 5 done (ing,guess,fuzz)
eugene-okulik/python-magic pull request #44
Opened 2023-08-23 15:01 UTC by kirylhlazkou

2023-08-24 15:16 UTC, eugene-okulik requested changes

2023-08-24 15:16 UTC, eugene-okulik commented on homework/kiryl_hlazkou/Homework_5/Task1.py
> +       'at,dignissim vitae libero.'
Переносы теста делаются с помощью скобок и без использования `\`

2023-08-24 15:16 UTC, eugene-okulik commented on homework/kiryl_hlazkou/Homework_5/Task1.py
> +print(' '.join(new_text))
Новый текст в итоге сдержит только слова, которые без знаков препинания. Тебе нужно или одну строчку раскомментить или последнюю строку в цикле подвинуть.

2023-08-29 15:16 UTC, kirylhlazkou commented on homework/kiryl_hlazkou/Homework_5/Task1.py
> +       'at,dignissim vitae libero.'
fixed

2023-09-05 06:48 UTC, eugene-okulik approved these changes

2023-09-05 06:48 UTC, merged