KH: Homework 6 done
eugene-okulik/python-magic pull request #47
Opened 2023-08-24 13:32 UTC by kirylhlazkou

2023-08-29 08:05 UTC, eugene-okulik requested changes

2023-08-29 08:05 UTC, eugene-okulik commented on homework/kiryl_hlazkou/Homework_6/Task1.py
> +        print(res2 * 2)
Если решать эту задачу так как у тебя, то нет смысла создавать эту функцию. Этот код мог бы быть написан и без функции. Но, если присмотреться, то здесь три раза выполняется одно и то же: одно число умножается на другое. И три раза в коде написано это действие. Но функция может помочь нам избежать такого.

2023-08-29 08:05 UTC, eugene-okulik commented on homework/kiryl_hlazkou/Homework_6/Task2.py
> +        print(key * value)
Эта функция здесь существует просто для того, чтобы была функция. И ее наличие заставляет нас написать еще больше кода, ведь эту функцию теперь нужно вызвать. Такой подход используется, для добавления структуры коду. Но эта программа очень простая и отсутствие функции не ухудшит ее читаемость.

2023-10-04 15:37 UTC, kirylhlazkou commented on homework/kiryl_hlazkou/Homework_6/Task1.py
> +        print(res2 * 2)
fixed

2023-10-04 15:37 UTC, kirylhlazkou commented on homework/kiryl_hlazkou/Homework_6/Task2.py
> +        print(key * value)
fixed

2023-10-06 06:43 UTC, eugene-okulik requested changes
В первом задании всё еще в трех местах одно число умножается на другое. Та функция, которая написана не имеет смысла - ты еще не переиспользуешь несколько раз. Но можно написать функцию, которую ты будешь 3 раза использовать и не писать один и тот же код.

2023-10-06 08:58 UTC, kirylhlazkou commented
> В первом задании всё еще в трех местах одно число умножается на другое. Та функция, которая написана не имеет смысла - ты еще не переиспользуешь несколько раз. Но можно написать функцию, которую ты будешь 3 раза использовать и не писать один и тот же код.

fixed

2023-10-10 12:43 UTC, eugene-okulik approved these changes

2023-10-10 12:43 UTC, merged