igor: homework 10(class1) completed
eugene-okulik/python-magic pull request #64
Opened 2023-09-03 15:18 UTC by IgorMakhon

2023-09-06 06:22 UTC, eugene-okulik requested changes

2023-09-06 06:22 UTC, eugene-okulik commented on homework/igor_mahon/homework_10_classes1/task1.py
> +        self.pages = number_pages
Название, автор и страницы умеет заполнять родительский класс, для того, чтобы он это сделал, нужно вызвать метод `__init__` родительского класса.

2023-09-06 06:22 UTC, eugene-okulik commented on homework/igor_mahon/homework_10_classes1/task1.py
> +    grade = 10
Все книги будут для 10 класса?

2023-09-06 06:22 UTC, eugene-okulik commented on homework/igor_mahon/homework_10_classes1/task1.py
> +    homework = False
Во всех учебниках нет домашних заданий?

2023-09-06 06:22 UTC, eugene-okulik commented on homework/igor_mahon/homework_10_classes1/task1.py
> +    international_standard_book_number = 122143242342425435
У всех книг одинаковый ISBN?

2023-09-10 10:16 UTC, IgorMakhon commented on homework/igor_mahon/homework_10_classes1/task1.py
> +        self.pages = number_pages
Учту, спасибо

2023-09-10 10:17 UTC, IgorMakhon commented on homework/igor_mahon/homework_10_classes1/task1.py
> +    grade = 10
Судя по критерием в ДЗ, то да:
"Какие-то из атрибутов будут общими для всех книг (материал, наличие текста), какие-то индивидуальными."
Слово "какие-то" позволяет так считать. 

Но судя по комменту нужно делать по-другому :), сделаю согласно новых требований и пришлю на проверку

2023-09-10 10:17 UTC, IgorMakhon commented on homework/igor_mahon/homework_10_classes1/task1.py
> +    homework = False
Судя по критерием в ДЗ, то да:
"Какие-то из атрибутов будут общими для всех книг (материал, наличие текста), какие-то индивидуальными."
Слово "какие-то" позволяет так считать

Но судя по комменту нужно делать по-другому :), сделаю согласно новых требований и пришлю на проверку

2023-09-10 10:17 UTC, IgorMakhon commented on homework/igor_mahon/homework_10_classes1/task1.py
> +    international_standard_book_number = 122143242342425435
Судя по критерием в ДЗ, то да:
"Какие-то из атрибутов будут общими для всех книг (материал, наличие текста), какие-то индивидуальными."
Слово "какие-то" позволяет так считать

Но судя по комменту нужно делать по-другому :), сделаю согласно новых требований и пришлю на проверку

2023-09-12 07:09 UTC, eugene-okulik commented on homework/igor_mahon/homework_10_classes1/task1.py
> +    grade = 10
Так то ж было для книг. Для учебников такое не написано.

2023-09-12 07:10 UTC, eugene-okulik commented on homework/igor_mahon/homework_10_classes1/task1.py
> +    international_standard_book_number = 122143242342425435
Ну, какие-то общие, какие-то индивидуальные. material и text_on_pages общие, ISBN индивидуальное. Вроде всё соответствует заданию. ))

2023-09-12 07:22 UTC, eugene-okulik approved these changes
В комменте еще одна штука, которуя я проглядел при первой проверке, но это уже мелочь.

2023-09-12 07:22 UTC, eugene-okulik commented on homework/igor_mahon/homework_10_classes1/task1.py
> +book2 = Book('Горе от ума том2', 'Грибоедов', 100, True, 4234324234232)
В задании было 

> После создания пометьте одну книгу как зарезервированную.

Но ты ее помечаешь зарезервированной уже при создании.

2023-09-12 07:22 UTC, merged