igor: homework 11(oop) completed
eugene-okulik/python-magic pull request #80
Opened 2023-09-11 17:09 UTC by IgorMakhon

2023-09-15 06:44 UTC, eugene-okulik requested changes

2023-09-15 06:44 UTC, eugene-okulik commented on homework/igor_mahon/homework_11_OOP/task1.py
> +            print(f' - The flower {flower.name} has the freshness {flower.freshness} in the bouquet')
Всё отлично кроме того, что этот метод сразу распечатывает результат в том формате, в котором ты задумал. Лучше было бы если бы этот метод возвращал отсортированный список цветов, который у тебя хранится в переменной `self.flowers`. Тогда там внизу можно будет делать так: 
```python
for flower in bouquet1.sort_by_freshness():
    print(flower.name)
    print(flower.color)
```
Или этот метод вообще может ничего не возвращать, т.к. он изменяет сортировку во всем букете и после вызова `bouquet1.sort_by_freshness()` можно будет делать:
```python
for flower in bouquet1.flowers:
    print(flower.name)
    print(flower.color)
```
То есть тот, кто пользуется объектами этого класса сам сможет решать что ему нужно распечатать.

2023-09-15 06:44 UTC, eugene-okulik commented on homework/igor_mahon/homework_11_OOP/task1.py
> +            print(f"Цветок '{match[0]}' имеет параметр '{match[1]}' в букете")
А вот этот метод точно должен возвращать список. Так как пользователь этого класса может хотеть найти все желтые цветы, а потом понять какие названия (или срок жизни или цена) у тех цветов, которые остались.

2023-10-07 13:35 UTC, IgorMakhon commented on homework/igor_mahon/homework_11_OOP/task1.py
> +            print(f"Цветок '{match[0]}' имеет параметр '{match[1]}' в букете")
Хорошо, я поправил, теперь метод возвращает список цветов.

2023-10-07 13:35 UTC, IgorMakhon commented on homework/igor_mahon/homework_11_OOP/task1.py
> +            print(f' - The flower {flower.name} has the freshness {flower.freshness} in the bouquet')
Хорошо, я поправил, теперь метод возвращает отсортированный список цветов.

2023-10-10 13:29 UTC, merged