KH: Homework 12 Date Done
eugene-okulik/python-magic pull request #90
Opened 2023-09-17 09:24 UTC by kirylhlazkou

2023-09-24 06:57 UTC, eugene-okulik requested changes
Главное, что нужно изменить - это брать файл из репозитория, а не из интернета.  
И подумай как избавиться от копипаста кода

2023-09-24 06:57 UTC, eugene-okulik commented on homework/kiryl_hlazkou/Homework_12/Task1.py
> +response = requests.get(github_url)
А зачем ты его из гитхаба выкачиваешь? Этот файлик ведь хранится в той же репе, где ты пишешь программу.

2023-09-24 06:57 UTC, eugene-okulik commented on homework/kiryl_hlazkou/Homework_12/Task1.py
> +third_date_time = datetime.datetime.strptime(third_date, '%Y-%m-%d %H:%M:%S.%f')
В строчках от 13 до 23 ты по три раза повторяешь оодно и то же действие. Нет идей как это сделать так, чтобы не копипастить один и тот же код?

2023-09-24 06:57 UTC, eugene-okulik commented on homework/kiryl_hlazkou/Homework_12/Task1.py
> +new_date = first_date_time + relativedelta(years=3)
О, прикольно что нашел `relativedelta`

2023-10-04 16:48 UTC, kirylhlazkou commented on homework/kiryl_hlazkou/Homework_12/Task1.py
> +response = requests.get(github_url)
fixed

2023-10-04 16:48 UTC, kirylhlazkou commented on homework/kiryl_hlazkou/Homework_12/Task1.py
> +third_date_time = datetime.datetime.strptime(third_date, '%Y-%m-%d %H:%M:%S.%f')
fixed

2023-10-06 06:47 UTC, eugene-okulik approved these changes

2023-10-06 06:47 UTC, merged