Novolodskiy: homework analyzer
eugene-okulik/python-magic pull request #94
Opened 2023-09-23 18:21 UTC by Novolodskiy

2023-10-03 15:56 UTC, eugene-okulik requested changes
Вообще, по функциональности всё круто. Но чтобы понять как мне передать путь мне пришлось вчитаться в код и узнать, что путь нужно писать от папки homework. Но если этим пользоваться вне нашего проекта и логи лежат где-то совсем в другом месте, то нет шанса их скормить.

2023-10-03 15:56 UTC, eugene-okulik commented on homework/dima_novolodskiy/Logs_Analyzer/analyzer.py
> +if args.file is not None:
Можно было для аргумента `file` поставить что он required и тогда можно было бы и не проверять ввели ли там путь к файлу.

2023-10-03 15:56 UTC, eugene-okulik commented on homework/dima_novolodskiy/Logs_Analyzer/analyzer.py
> +    new_path = os.path.join(my_path, path)
Ты всё-таки решил заморочиться с путем. И сейчас, как не передай путь к файлу, ничего не получится если файл с логами лежит не рядом с файлом программы. Если чо, я пытаюсь так к нему обратиться:
```
python analyzer.py ../../eugene_okulik/data/logs/rpe-api-error.2022-02-03.0.log
```
или 
```
python analyzer.py home/eugene/projects/python-magic/eugene_okulik/data/logs/rpe-api-error.2022-02-03.0.log
```
И Я не представляю как натравить программу на другую папку, только если логи подвинуть.

2023-10-04 23:36 UTC, Novolodskiy commented on homework/dima_novolodskiy/Logs_Analyzer/analyzer.py
> +        print(Fore.LIGHTYELLOW_EX + f'[{log}]' + ' ' + Fore.LIGHTWHITE_EX + text_log[
Я здесь не сбрасывал. Он просто тусклый по умолчанию

2023-10-06 07:00 UTC, eugene-okulik approved these changes
:+1:

2023-10-06 07:00 UTC, merged